macro(TARGET_DRACO)
    if (ANDROID)
        set(INSTALL_DIR ${HIFI_ANDROID_PRECOMPILED}/draco)
        set(DRACO_INCLUDE_DIRS "${INSTALL_DIR}/include" CACHE STRING INTERNAL)
        set(LIB_DIR ${INSTALL_DIR}/lib)
        list(APPEND DRACO_LIBRARIES ${LIB_DIR}/libdraco.a)
        list(APPEND DRACO_LIBRARIES ${LIB_DIR}/libdracodec.a)
        list(APPEND DRACO_LIBRARIES ${LIB_DIR}/libdracoenc.a)
        target_link_libraries(${TARGET_NAME} ${DRACO_LIBRARIES})
    else()
        find_library(DRACO_LIBRARY_RELEASE draco PATHS ${VCPKG_INSTALL_ROOT}/lib NO_DEFAULT_PATH)
        find_library(DRACO_LIBRARY_DEBUG draco PATHS ${VCPKG_INSTALL_ROOT}/debug/lib NO_DEFAULT_PATH)
        select_library_configurations(DRACO)
        target_link_libraries(${TARGET_NAME} ${DRACO_LIBRARIES})
    endif()
endmacro()
